### ISSUE TITLE
Default settings problem and improvement suggestion

### ISSUE THREAD

**Issue by MFava91** [adamwalzer/vscode-code-replacer#1]
Hi Adam. 
First of all, thanks for your amazing extension. 
We have started to use it at work and it helps a lot.
We have noticed a few issues/possible improvement:

- the rules on default settings may cause some problem. If I wouldn't rule for `#000` I can't disable it;
- Changes in setting (rules) only apply after a visual studio code restart;
- We use your extension for replacing a name of a color with our variable. So we have `#red `and `#red-dark`. When I write the `#red-dark` the extensions suggest the two possible variables but replace every time the shortest. Same problem for example with `#fff` and `#fff9f9`. We have workaround this "_issue_" using the correct name (#red - #dark-red or with the help of [name that color](http://chir.ag/projects/name-that-color)). 

![code-replacer](https://user-images.githubusercontent.com/6460329/39082708-afc8edae-4557-11e8-8bc3-0c59c904cf19.gif)

So, can we do something about it? 
Maybe some improvement suggested are out of scope?

Thanks.

**Comment by adamwalzer** [comment]
Sorry. I'm just seeing this now. I will look into what I can do and get back to you. Thanks for filing this issue.

**Comment by adamwalzer** [comment]
Updated. Version 0.0.4 should solve your first two issues. For the third I would recommend changing your replacements to be `"#red;": "$brand-01;"` and `"#red-dark;": "$brand-02;"`.

**Comment by adamwalzer** [comment]
@MFava91 please let me know if this fixes your issue, and then we can close this ticket. Thanks for your help!

**Comment by MFava91** [comment]
@adamwalzer all seems works like a charm!
In the first point nothing to add.
In the second point, the only little thing that I've seen is that the update of the `codeReplacer.rules` is immediate, instead, the `codeReplacer.replaceOnSave` option need a full visual studio code restart (however it is not a big problem).
Nice "_workaround_" for the third point.

**Comment by adamwalzer** [comment]
@MFava91 `codeReplacer.replaceOnSave` should work without needing a refresh now.
