### ISSUE TITLE
Request: Support for regex capture groups

### ISSUE THREAD

**Issue by RichardJJG** [adamwalzer/vscode-code-replacer#2]
Hi, Adam,

Thanks very much for making this.

Might it be possible to support regex capture groups? 
A use case would be to add comments adjacent to code instead of just replacing it. 

For example:
"(#000)": "$1 "

would result in

#000 

Right now, $1 is just treated as a string, as best I can tell.

**Comment by adamwalzer** [comment]
I don't have a plan to implement this feature, but please feel free to create a pull request if you'd like.
